import type { Metadata } from "next"
import { Unbounded } from "next/font/google"
import "./globals.css"
import LayoutWrapper from "../components/layoutwrapper" // <-- новое

const unbounded = Unbounded({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={unbounded.className}>
      <body>
        <LayoutWrapper>
          {children}
        </LayoutWrapper>
      </body>
    </html>
  )
}